// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

public class AIScheduler
{
	private static AIScheduler instance;
	
	private AIScheduler() {}
	
	public static AIScheduler Instance
	{
		get 
		{
			if (instance == null)
			{
				instance = new AIScheduler();
			}
			return instance;
		}
	}

	public uint Schedule(Dictionary<uint, AIAgent> agents, Dictionary<uint, AICharacter> characters)
	{
		// simple getAction -> executeAction
		foreach(AIAgent agent in agents.Values)
		{
			if(agent.Active)
			{
				AIAction action = agent.MakeDecision();
				if(action != null && characters.ContainsKey(agent.CharacterId))
				{
					characters[agent.CharacterId].Actor.Execute(action);
				}
			}
		}
		return 0;
	}
}

