// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class AIBehaviorAggressive : AIBehavior
{
	private EnemySight enemySight;							// Reference to the EnemySight script.
	private PlayerHealth playerHealth;						// Reference to the PlayerHealth script.
	private LastPlayerSighting lastPlayerSighting;			// Reference to the last global sighting of the player.
	private Transform player;								// Reference to the player's transform.

	public AIBehaviorAggressive (AICharacter character)
	{
		enemySight = character.gameObject.GetComponent<EnemySight>();
		player = GameObject.FindGameObjectWithTag(Tags.player).transform;
		playerHealth = player.GetComponent<PlayerHealth>();
		lastPlayerSighting = GameObject.FindGameObjectWithTag(Tags.gameController).GetComponent<LastPlayerSighting>();
	}

	public override void Init()
	{
		// init
	}

	public override AIAction MakeDecision()
	{
		// If the player is in sight and is alive...
		if(enemySight.playerInSight && playerHealth.health > 0f)
			// ... shoot.
			return new AIAction(AIAgentManager.ActionId.Shoot, "Shoot in tha face");// Shooting();
		
		// If the player has been sighted and isn't dead...
		else if(enemySight.personalLastSighting != lastPlayerSighting.resetPosition && playerHealth.health > 0f)
			// ... chase.
			return new AIAction(AIAgentManager.ActionId.Chase, "Chase");
		
		// Otherwise...
		else
			// ... patrol.
			return new AIAction(AIAgentManager.ActionId.Patrol, "Patrol");
	}
}
