// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class AIBehaviorParanoid : AIBehavior
{
	private EnemySight enemySight;							// Reference to the EnemySight script.
	private PlayerHealth playerHealth;						// Reference to the PlayerHealth script.
	private LastPlayerSighting lastPlayerSighting;			// Reference to the last global sighting of the player.
	private Transform player;								// Reference to the player's transform.
	private AICharacter m_character;						// Reference to AICharacter using this behavior

	public AIBehaviorParanoid (AICharacter character)
	{
		m_character = character;
		enemySight = character.gameObject.GetComponent<EnemySight>();
		player = GameObject.FindGameObjectWithTag(Tags.player).transform;
		playerHealth = player.GetComponent<PlayerHealth>();
		lastPlayerSighting = GameObject.FindGameObjectWithTag(Tags.gameController).GetComponent<LastPlayerSighting>();
	}

	public override void Init()
	{
	}


	public override AIAction MakeDecision()
	{
		// If the player has been sighted and isn't dead...
		if(enemySight.playerInSight && playerHealth.health > 0f)
			// ... chase.
			return new AIAction(AIAgentManager.ActionId.Die, "Die");
		
		// Otherwise...
		else
			// ... patrol.
			return new AIAction(AIAgentManager.ActionId.Patrol, "Patrol");
	}
}
