// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public class AIAction
{
	private AIAgentManager.ActionId m_actionId;
	public AIAgentManager.ActionId ActionId
	{
		get
		{
			return m_actionId;
		}
	}

	private String m_description;
	public String Description
	{
		get
		{
			return m_description;
		}
	}

	private object[] m_arguments;
	public object[] Arguments
	{
		get
		{
			return m_arguments;
		}
	}

	public AIAction (AIAgentManager.ActionId actionId, String description, params object[] arguments)
	{
		m_actionId = actionId;
		m_description = description;
		m_arguments = arguments;
	}
}


